"""empty message

Revision ID: 15dd310875c3
Revises: 94577b055742
Create Date: 2025-06-10 14:14:33.424112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15dd310875c3'
down_revision: Union[str, None] = '94577b055742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=False),
    sa.Column('updatedTime', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_owner_id'), 'task', ['owner_id'], unique=False)
    op.create_table('task_attributes',
    sa.Column('taskId', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['task.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('taskId')
    )
    op.drop_constraint(None, 'user_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'user_attributes', 'user', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'user_attributes', 'user', ['userId'], ['id'])
    op.drop_table('task_attributes')
    op.drop_index(op.f('ix_task_owner_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
